name: 'Setup IOG librararies'
description: 'Installs libsodum, libsecp256k1 and libblst'
inputs:
  use-sodium-vrf:
    description: Use libsodium with VRF extension
    default: true

runs:
  env:
    LIBSODIUM: ${{ inputs.use-sodium-vrf && 'libsodium-vrf' || 'libsodium' }}
    URL_PREFIX: https://github.com/input-output-hk/iohk-nix/releases/tag/latest
  using: "composite"
  steps:
    - name: "[darwin] Install library dependencies"
      if: runner.os == 'macOS'
      shell: bash
      run: |
        brew install pkg-config

        mkdir __prep__
        pushd __prep__
          curl -sL ${URL_PREFIX}/macos.${LIBSODIUM}.pkg > libsodium.pkg
          curl -sL ${URL_PREFIX}/macos.libsecp256k1.pkg > libsecp256k1.pkg
          curl -sL ${URL_PREFIX}/macos.libblst.pkg      > libblst.pkg
          for pkg in *.pkg; do
            sudo installer -pkg $pkg -target /
          done
        popd
        rm -fR __prep__

        echo 'PKG_CONFIG_PATH=/usr/local/opt/cardano/lib/pkgconfig:$PKG_CONFIG_PATH' >> $GITHUB_ENV

    - name: "[windows] Install library dependencies"
      if: runner.os == 'Windows'
      shell: C:/msys64/usr/bin/bash.exe -e '{0}'
      env:
        MSYSTEM: MSYS
        # do not ever change to $HOME by yourself.
        CHERE_INVOKING: 1
        # do we want to inherit the path?
        # MSYS2_PATH_TYPE: inherit
      run: |
        /usr/bin/pacman --noconfirm -S \
          mingw-w64-x86_64-pkg-config

        mkdir __prep__
        pushd __prep__
          curl -sL ${URL_PREFIX}/msys2.${LIBSODIUM}.pkg.tar.zstd > libsodium.pkg.tar.zstd
          curl -sL ${URL_PREFIX}/msys2.libsecp256k1.pkg.tar.zstd > libsecp256k1.pkg.tar.zstd
          curl -sL ${URL_PREFIX}/msys2.libblst.pkg.tar.zstd      > libblst.pkg.tar.zstd
          for pkg in *.zstd; do
            /usr/bin/pacman --noconfirm -U $pkg
          done
        popd
        rm -fR __prep__

        echo 'PKG_CONFIG_PATH=C:\\msys64\mingw64\opt\cardano\lib\pkgconfig' >> $GITHUB_ENV
        # Add the `bin` folder, which contains all the .dlls on windows, so we
        # can find them.
        echo 'PATH=C:\\msys64\mingw64\opt\cardano\bin:$PATH'                >> $GITHUB_ENV

    - name: "[linux] Install library dependencies"
      if: runner.os == 'Linux'
      shell: bash
      run: |
        mkdir __prep__
        pushd __prep__
          curl -sL ${URL_PREFIX}/debian.${LIBSODIUM}.deb > libsodium.deb
          curl -sL ${URL_PREFIX}/debian.libsecp256k1.deb > libsecp256k1.deb
          curl -sL ${URL_PREFIX}/debian.libblst.deb      > libblst.deb
          for pkg in *.deb; do
            sudo dpkg -i $pkg
          done
        popd
        rm -fR __prep__

        echo 'PKG_CONFIG_PATH=/usr/local/opt/cardano/lib/pkgconfig:$PKG_CONFIG_PATH' >> $GITHUB_ENV
        echo 'LD_LIBRARY_PATH=/usr/local/opt/cardano/lib:$LD_LIBRARY_PATH'           >> $GITHUB_ENV
