name: 'Setup IOG librararies'
description: 'Installs libsodum, libsecp256k1 and libblst'

outputs:
  prefix:
    description: "Installed Location"
    value: ${{ steps.prefix.outputs.prefix }}

runs:
  using: "composite"
  steps:
    - name: Read versions
      id: libs
      shell: bash
      run: echo "PACKAGE_JSON=$(jq -c . < libs.json)" >> $GITHUB_ENV

    - name: Compute installation location
      id: prefix
      shell: bash
      run: |
        PREFIX=${{ runner.os == Windows && '/mingw64' || '/usr/local' }}
        echo "PREFIX=$PREFIX" | tee -a "$GITHUB_ENV"
        echo "prefix=$PREFIX" >> $GITHUB_OUTPUT

    - name: secp256k1 - checkout
      shell: bash
      run: |
        mkdir -p ${{ github.workspace }}/extras/sources/secp256k1
        cd ${{ github.workspace }}/extras/sources/secp256k1
        curl ${{ env.libs.secp256k1 }} | tar xf -

    - name: "secp256k1 - posix - install"
      if: runner.os != 'Windows'
      shell: bash
      working-directory: ${{ github.workspace }}/extras/sources/secp256k1
      env:
        CI_SECP_FLAGS: "--prefix=${{ env.SECP256K1_PREFIX }}"
        CI_SECP_INSTALL_CMD: sudo
      run: bash -x "${{ github.action_path }}/build-and-install.sh"

    - name: "secp256k1 - windows - install"
      if: runner.os == 'Windows'
      shell: pwsh
      working-directory: ${{ github.workspace }}/extras/sources/secp256k1
      env:
        # Same environment as tmate action
        MSYS2_PATH_TYPE: inherit
        MSYSTEM: MINGW64
        CHERE_INVOKING: 1
        CI_SECP_FLAGS: "--prefix=${{ env.SECP256K1_PREFIX }}"
      run: C:\\msys64\\usr\\bin\\bash.exe "${{ github.action_path }}/build-and-install.sh"
