name: 'Setup IOG librararies'
description: 'Installs libsodum, libsecp256k1 and libblst'
inputs:
  ghc-version:
    description: Version of GHC to install
    default: ''

  cabal-version:
    description: Version of cabal to install
    default: ''

outputs:
  prefix:
    description: "Installed Location"
    value: ${{ steps.prefix.outputs.prefix }}

runs:
  using: "composite"
  steps:
    - name: "[darwin] Ensure pkg-config is available"
      if: runner.os == 'macOS'
      shell: bash
      run: brew install pkg-config

    - name: "[windows] Ensure pkg-config is available"
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        ghcup run -- pacman --noconfirm -S `
          mingw-w64-x86_64-pkg-config `
          mingw-w64-x86_64-openssl

    - name: "[windows] Install sodium, secp256k1, and blst"
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        ls ${{ github.action_path }}
        ghcup run -- pacman --noconfirm -U `
          .github/dist/msys2/libsodium-x86_64-w64-mingw32-1.0.18.pkg.tar.zstd