name: 'Setup IOG librararies'
description: 'Installs libsodum, libsecp256k1 and libblst'
inputs:
  ghc-version:
    description: Version of GHC to install
    default: ''

  cabal-version:
    description: Version of cabal to install
    default: ''

outputs:
  prefix:
    description: "Installed Location"
    value: ${{ steps.prefix.outputs.prefix }}

runs:
  using: "composite"
  steps:
    - name: "[darwin] Ensure pkg-config is available"
      if: runner.os == 'macOS'
      shell: bash
      run: brew install pkg-config

    - name: "[windows] Ensure pkg-config is available"
      if: runner.os == 'Windows'
      shell: C:/msys64/usr/bin/env.exe MSYSTEM=MSYS C:/msys64/usr/bin/bash.exe -e '{0}'
      env:
        MSYSTEM: MSYS
        # do not ever change to $HOME by yourself.
        CHERE_INVOKING: 1
        # do we want to inherit the path?
        # MSYS2_PATH_TYPE: inherit
      run: |
        echo $PATH
        pacman --noconfirm -S \
          mingw-w64-x86_64-pkg-config \
          mingw-w64-x86_64-openssl

        pacman --noconfirm -U \
          ${{ github.action_path }}.github/dist/msys2/libsodium-x86_64-w64-mingw32-1.0.18.pkg.tar.zstd
