name: 'Setup IOG librararies'
description: 'Installs libsodum, libsecp256k1 and libblst'
inputs:
  ghc-version:
    description: Version of GHC to install
    default: ''

  cabal-version:
    description: Version of cabal to install
    default: ''

outputs:
  prefix:
    description: "Installed Location"
    value: ${{ steps.prefix.outputs.prefix }}

runs:
  using: "composite"
  steps:
    - name: "[darwin] Install library dependencies"
      if: runner.os == 'macOS'
      shell: bash
      env:
        URL_PREFIX: https://ci.zw3rk.com/job/input-output-hk-iohk-nix/pullrequest-533
      run: |
        brew install pkg-config

        sudo installer installer -target / -pkg <(curl -sL ${URL_PREFIX}/macos.libsodium/latest/download-by-type/file/binary-dist)
        sudo installer installer -target / -pkg <(curl -sL ${URL_PREFIX}/macos.libsecp256k1/latest/download-by-type/file/binary-dist)
        sudo installer installer -target / -pkg <(curl -sL ${URL_PREFIX}/macos.libblst/latest/download-by-type/file/binary-dist)

        echo 'PKG_CONFIG_PATH=/usr/local/optcardano/lib/pkgconfig:$PKG_CONFIG_PATH' >> $GITHUB_ENV

    - name: "[windows] Install library dependencies"
      if: runner.os == 'Windows'
      shell: C:/msys64/usr/bin/bash.exe -e '{0}'
      env:
        MSYSTEM: MSYS
        # do not ever change to $HOME by yourself.
        CHERE_INVOKING: 1
        # do we want to inherit the path?
        # MSYS2_PATH_TYPE: inherit
        URL_PREFIX: https://ci.zw3rk.com/job/input-output-hk-iohk-nix/pullrequest-533
      run: |
        /usr/bin/pacman --noconfirm -S \
          mingw-w64-x86_64-pkg-config \
          mingw-w64-x86_64-openssl

        /usr/bin/pacman --noconfirm -U <(curl -sL ${URL_PREFIX}/msys2.libsodium/latest/download-by-type/file/binary-dist)
        /usr/bin/pacman --noconfirm -U <(curl -sL ${URL_PREFIX}/msys2.libsecp256k1/latest/download-by-type/file/binary-dist)
        /usr/bin/pacman --noconfirm -U <(curl -sL ${URL_PREFIX}/msys2.libblst/latest/download-by-type/file/binary-dist)

        echo 'PKG_CONFIG_PATH=C:\\msys64\mingw64\opt\cardano\lib\pkgconfig' >> $GITHUB_ENV
