name: 'Setup IOG librararies'
description: 'Installs libsodum, libsecp256k1 and libblst'
inputs:
  ghc-version:
    description: Version of GHC to install
    default: ''

  cabal-version:
    description: Version of cabal to install
    default: ''

outputs:
  prefix:
    description: "Installed Location"
    value: ${{ steps.prefix.outputs.prefix }}

runs:
  using: "composite"
  steps:
    - name: "[darwin] Install library dependencies"
      if: runner.os == 'macOS'
      shell: bash
      env:
        URL_PREFIX: https://ci.zw3rk.com/job/input-output-hk-iohk-nix/pullrequest-533
      run: |
        brew install pkg-config

        mkdir __prep__
        pushd __prep__
          curl -sL ${URL_PREFIX}/macos.libsodium/latest/download-by-type/file/binary-dist    > libsodium.pkg
          curl -sL ${URL_PREFIX}/macos.libsecp256k1/latest/download-by-type/file/binary-dist > libsecp256k1.pkg
          curl -sL ${URL_PREFIX}/macos.libblst/latest/download-by-type/file/binary-dist      > libblst.pkg
          ls .
          for pkg in *.pkg; do
            sudo installer -pkg $pkg -target /
          done
        popd
        rm -fR __prep__

        echo 'PKG_CONFIG_PATH=/usr/local/opt/cardano/lib/pkgconfig:$PKG_CONFIG_PATH' >> $GITHUB_ENV

    - name: "[windows] Install library dependencies"
      if: runner.os == 'Windows'
      shell: C:/msys64/usr/bin/bash.exe -e '{0}'
      env:
        MSYSTEM: MSYS
        # do not ever change to $HOME by yourself.
        CHERE_INVOKING: 1
        # do we want to inherit the path?
        # MSYS2_PATH_TYPE: inherit
        URL_PREFIX: https://ci.zw3rk.com/job/input-output-hk-iohk-nix/pullrequest-533
      run: |
        /usr/bin/pacman --noconfirm -S \
          mingw-w64-x86_64-pkg-config \
          mingw-w64-x86_64-openssl

        mkdir __prep__
        pushd __prep__
          curl -sL ${URL_PREFIX}/msys2.libsodium/latest/download-by-type/file/binary-dist    > libsodium.pkg.tar.zstd
          curl -sL ${URL_PREFIX}/msys2.libsecp256k1/latest/download-by-type/file/binary-dist > libsecp256k1.pkg.tar.zstd
          curl -sL ${URL_PREFIX}/msys2.libblst/latest/download-by-type/file/binary-dist      > libblst.pkg.tar.zstd
          ls .
          for pkg in *.zstd; do
            /usr/bin/pacman --noconfirm -U $pkg
          done
        popd
        rm -fR __prep__

        echo 'PKG_CONFIG_PATH=C:\\msys64\mingw64\opt\cardano\lib\pkgconfig' >> $GITHUB_ENV

    - name: "[linux] Install library dependencies"
      if: runner.os == 'Linux'
      shell: bash
      env:
        URL_PREFIX: https://ci.zw3rk.com/job/input-output-hk-iohk-nix/pullrequest-533
      run: |
        mkdir __prep__
        pushd __prep__
          curl -sL ${URL_PREFIX}/debian.libsodium/latest/download-by-type/file/binary-dist    > libsodium.deb
          curl -sL ${URL_PREFIX}/debian.libsecp256k1/latest/download-by-type/file/binary-dist > libsecp256k1.deb
          curl -sL ${URL_PREFIX}/debian.libblst/latest/download-by-type/file/binary-dist      > libblst.deb
          ls .
          for pkg in *.deb; do
            sudo dpkg -i $pkg
          done
        popd
        rm -fR __prep__

        echo 'PKG_CONFIG_PATH=/usr/local/opt/cardano/lib/pkgconfig:$PKG_CONFIG_PATH' >> $GITHUB_ENV

