steps:
  - label: hydra-eval-errors
    command: 'nix-build -A hydraEvalErrors && ./result/bin/hydra-eval-errors.py'
    branches: "master bors/*"
    agents:
      system: x86_64-linux

  - label: ":pipeline: Skeleton project pipelines"
    command:
      - 'buildkite-agent pipeline upload skeleton/.buildkite/pipeline.yml'
      - 'buildkite-agent pipeline upload skeleton/.buildkite/nightly.yml'
    branches: "master bors/*"
    agents:
      system: x86_64-linux
