name: Sanity
on: push

jobs:
  check:
    name: Ensure libs.json matches nix configuration.
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=https://github.com/nixos/nixpkgs/archive/release-22.11.tar.gz
    - run: |
        nix-shell -p jq -p diff --run 'diff libs.json <(nix eval --json .#lib-srcs | jq .)'
