name: Validate IOG Core GH Action
on: push
permissions:
  contents: read
jobs:
  integration:
    strategy:
        fail-fast: false
        matrix:
          os: [ubuntu-latest, windows-latest, macos-latest]
    name: GitHub Action integration test
    runs-on: ${{ matrix.os }}
    steps:
    - uses: input-output-hk/actions/base@dbb6ea6d50ffc37a2d481fd8047aff028bac3223 # latest
    - name: Check pkg-config
      run: |
        pkg-config --libs libblst
        pkg-config --libs libsodium
        pkg-config --libs libsecp256k1
