name: Package foreign libs
on: push
jobs:

  matrix:
    name: ⬜ Generate list of jobs
    runs-on: ubuntu-latest
    outputs:
      jobs: ${{ steps.matrix.outputs.jobs }}
    steps:
    - id: matrix
      uses: msys2/setup-msys2/matrix@main
      with:
        systems: mingw64

  libsoidum:
    name: build libsodium for msys2
    needs: matrix
    uses: msys2/setup-msys2/.github/workflows/PKGBUILD.yml@main
    with:
      name: libsodium
      matrix: ${{ needs.matrix.outputs.jobs }}
      path: packaging/msys2/mingw-w64-libsodium
    # runs-on: windows-latest
    # steps:
    # - uses: actions/checkout@v3
    # - name: Read versions
    #   id: libs
    #   shell: bash
    #   run: echo "libs=$(jq -c . < libs.json)" >> $GITHUB_ENV
    # - name: build
    #   shell: msys2
    #   run: |
    #     cd packaging/msys2/mingw-w64-libsodium
    #     MINGW_ARCH=mingw64 makepkg-mingw -sCLf
    #     ls